theme: jekyll-theme-minimal
title: Remy Matos
description: Cybersecurity Engineer at Confidential
logo: https://media.licdn.com/dms/image/v2/D4E35AQEHmSJBNrtWyQ/profile-framedphoto-shrink_400_400/profile-framedphoto-shrink_400_400/0/1726078363949?e=1727204400&v=beta&t=FcOoHYozB9ketYu8Hz0lJE5IxY0_uqahnZS6glKAEDQ
show_downloads: false